[project]
name = "rednote-crawler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "browserforge>=1.2.4",
    "playwright>=1.58.0",
    "playwright-stealth>=2.0.2",
    "pyyaml>=6.0.3",
]
